### PR TITLE
Mark testing

### PR DESCRIPTION
**Pull request by frenchy-mark**
#15 is addressed by the 1st commit.  Although only in part, the non-unique result sets have their own case which requires additional work.
#17 is addressed by the 2nd commit.

### CODE REVIEW

**Comment by frenchy-mark** [comment]
Not really sure if I'm updating my previous pull request with the latest commit or if I'm starting a new one that has all 3 commits from this evening.  Here goes...

**Comment by frenchy-mark** [comment]
@Warthog710 how do you test the code you are merging?  Are you reading it or actually running through some test cases with the code in question?
@t-jones any pro tips?

**Comment by Warthog710** [comment]
@frenchy-mark 
As of now, I am reading the code. Should I be downloading the changes and running them to verify they do what the author says they do?

**Comment by frenchy-mark** [comment]
I would think so, but I'm interested in Tim's thoughts.

**Pull request merged**
